services:
  DMP\TransactionalBundle\Aop\TransactionalPointcut:
    public: true
    autowire: true
    tags:
      - { name: jms_aop.pointcut, interceptor: DMP\TransactionalBundle\Aop\TransactionalInterceptor}
  DMP\TransactionalBundle\Aop\TransactionalInterceptor:
    public: true
    autowire: true
  DMP\TransactionalBundle\Doctrine\OrmTransactionManager:
    public: true
    autowire: true
